apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: 80-tcp
      port: 80
      targetPort: 80
    - name: 443-tcp
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: caddy
