apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: livegrep-frontend
  name: livegrep-frontend
spec:
  ports:
    - name: "8910"
      port: 8910
      targetPort: 8910
  selector:
    io.kompose.service: livegrep-frontend
