apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: livegrep-backend-linux
  name: livegrep-backend-linux
spec:
  ports:
    - name: "9898"
      port: 9898
      targetPort: 9898
  selector:
    io.kompose.service: livegrep-backend-linux
