apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: livegrep-backend-linux
  name: livegrep-backend-linux
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: 'docker.io/livegrep/base:'
      name: ""
      referencePolicy:
        type: ""
