apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: livegrep-nginx
  name: livegrep-nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: livegrep-nginx
